Import('SFW_ROOT')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd, SFW_ROOT + '/firmware/include']

if GetDepend(['SOC_LPC_SERIES']):
    src = ['flash_api.c']
else:
    src = Glob('*.c')

group = DefineGroup('flashiap', src, depend = [], CPPPATH = CPPPATH)

Return('group')
