from building import *

# The set of source files associated with this SConscript file.
src = Glob('*.c')
cwd = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('mflash', src, depend = ['OTA_AWS'], CPPPATH = CPPPATH)

Return('group')
