import os
from building import *
Import('sfwprofile')

cwd = GetCurrentDir()
group = []

# add the general drivers.
src = Split("""
sfw.c
""")

if GetDepend(['OTA_SUPPORT']):
    src += ['ota_flag/sbl_ota_flag.c']

CPPPATH = [cwd, cwd + '/include', cwd + '/freertos', cwd + '/ota_flag']
ASPATH = [cwd + '/freertos']
CPPDEFINES = []

if GetDepend(['OTA_ALIYUN']):
    if sfwprofile.PLATFORM == 'gcc':
        CPPDEFINES = ['_TIMEVAL_DEFINED']

group = DefineGroup('firmware', src, depend = [''], CPPPATH = CPPPATH, ASPATH = ASPATH, CPPDEFINES = CPPDEFINES)

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
